require: rubocop-rspec
AllCops:
  NewCops: enable
  SuggestExtensions: false
Metrics/MethodLength:
  Max: 15
RSpec/MultipleMemoizedHelpers:
  Enabled: false
RSpec/NestedGroups:
  Max: 8
RSpec/SubjectStub:
  Enabled: false
RSpec/ExampleLength:
  Max: 15
